/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.User;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.Network.Network;
import Business.Organization.LocalPoliceDepartmentOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VictimWorkRequest;
import javax.swing.JOptionPane;

/**
 *
 * @author likha
 */
public class CaseRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CaseRegistrationJPanel
     */
    JPanel container;
    EcoSystem system;
    Enterprise enterprise;
    Network network;
    Organization organization;

    public CaseRegistrationJPanel(JPanel container, EcoSystem system, Enterprise enterprise, Network network, Organization organization) {
        initComponents();
        this.container = container;
        this.system = system;
        this.enterprise = enterprise;
        this.network = network;
        this.organization = organization;

        populateComboNetwork();

    }

    public void populateComboNetwork() {

        comboNetwork.removeAllItems();

        for (Network network : system.getNetworkList()) {
            comboNetwork.addItem(network);
        }

    }

    public void populateComboEnterprise(Network network) {

        comboEnterprise.removeAllItems();

        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            comboEnterprise.addItem(enterprise);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAdd1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtAdd2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCaseDesc = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();
        comboEnterprise = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(txtAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 71, 175, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Address Line 2 :");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 118, -1, -1));
        add(txtAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 115, 175, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Address Line 1 :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 74, -1, -1));

        txtCaseDesc.setColumns(20);
        txtCaseDesc.setRows(5);
        jScrollPane1.setViewportView(txtCaseDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 173, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Area of Residence of victim");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 22, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Case Description :");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, -1));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 70, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("City:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 150, -1, -1));

        comboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 150, 175, -1));

        comboEnterprise.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEnterpriseActionPerformed(evt);
            }
        });
        add(comboEnterprise, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 197, 175, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Police Dept.:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        VictimWorkRequest victimWorkRequest = new VictimWorkRequest();
        victimWorkRequest.setAddressLine1(txtAdd1.getText());
        victimWorkRequest.setAddressLine2(txtAdd2.getText());
        victimWorkRequest.setCaseDesc(txtCaseDesc.getText());
        victimWorkRequest.setArea(comboEnterprise.getSelectedItem().toString());

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {

                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof LocalPoliceDepartmentOrganization) {
                        victimWorkRequest.setStatus("Reported");

                        o.getWorkQueue().getWorkRequestList().add(victimWorkRequest);

                    }
                }
            }
        }

        JOptionPane.showMessageDialog(null, "Your case is successfully reported!");

        txtAdd1.setText("");
        txtAdd2.setText("");
        txtCaseDesc.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        Network network = (Network) comboNetwork.getSelectedItem();
        if (network != null) {
            populateComboEnterprise(network);
            // populateComboOrganization(enterprise);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_comboNetworkActionPerformed

    private void comboEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEnterpriseActionPerformed

//                       // TODO add your handling code here:
    }//GEN-LAST:event_comboEnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboEnterprise;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAdd1;
    private javax.swing.JTextField txtAdd2;
    private javax.swing.JTextArea txtCaseDesc;
    // End of variables declaration//GEN-END:variables
}
