/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.LocalPoliceDepartment;
import Business.CentralPoliceDepartment.Dealer;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.LocalPoliceDepartmentOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.VictimWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author likha
 */
public class LocalPoliceDepartmentWorkArea extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    LocalPoliceDepartmentOrganization organization;
    Enterprise enterprise;
    EcoSystem business;
    ArrayList<WorkRequest> listofreq;    
    ArrayList<Employee> emp;

    /**
     * Creates new form LocalPoliceDepartmentWorkArea
     */
    public LocalPoliceDepartmentWorkArea(JPanel userProcessContainer, UserAccount account, LocalPoliceDepartmentOrganization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.business = business;
        this.organization = organization;
        this.listofreq = organization.getWorkQueue().getWorkRequestList();
        this.emp = organization.getEmployeeDirectory().getEmployeeList();
        setSize(1000, 1000);
        populateRequestTable(emp);
        populateDealerTable();
        comboArea.removeAllItems();
        comboArea.addItem(enterprise.toString());
    }

    public void populateDealerTable() {

        DefaultTableModel model = (DefaultTableModel) dealerTable.getModel();
        model.setRowCount(0);

        for (Dealer dealer : organization.getDealerCatalog().getDealerCatalog()) {
            Object[] row = new Object[4];

            row[0] = dealer;
            row[1] = dealer.getAlias();
            row[2] = dealer.getActivityArea();
            row[3] = dealer.getStatus();
            model.addRow(row);
        }
    }

    public void populateRequestTable(ArrayList<Employee> emp) {
        DefaultTableModel model = (DefaultTableModel) requestTable.getModel();
        model.setRowCount(0);

        for (WorkRequest work : listofreq) {

            if (work instanceof VictimWorkRequest) {
                if (((VictimWorkRequest) work).getArea().equals(enterprise.toString())) {

                    Object[] row = new Object[4];

                    row[0] = ((VictimWorkRequest) work).getAddressLine1();
                    row[2] = ((VictimWorkRequest) work).getCaseDesc();
                    row[1] = work;

                    row[3] = ((VictimWorkRequest) work).getArea();
                    model.addRow(row);

                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        reqBtn = new javax.swing.JButton();
        btnComplete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCaseDesc = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        dealerTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        txtname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAlias = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        activeRadioBtn = new javax.swing.JRadioButton();
        inActiveRadioBtn = new javax.swing.JRadioButton();
        comboArea = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Local Police Department");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 28, -1, -1));

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Address", "Status", "Description", "Area"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 64, 470, 171));

        btnDelete.setText("Delete request");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 392, 150, -1));

        reqBtn.setText("Assign To Me");
        reqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqBtnActionPerformed(evt);
            }
        });
        add(reqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 306, 150, -1));

        btnComplete.setText("Complete");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });
        add(btnComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 349, 149, -1));

        txtCaseDesc.setEditable(false);
        txtCaseDesc.setColumns(20);
        txtCaseDesc.setRows(5);
        txtCaseDesc.setEnabled(false);
        jScrollPane1.setViewportView(txtCaseDesc);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 264, 279, 157));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Case Description:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 235, -1, -1));

        jButton1.setText("Case Description");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 263, 150, -1));

        dealerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Alias", "Area", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(dealerTable);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 64, -1, 171));

        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 416, 173, -1));

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnameKeyTyped(evt);
            }
        });
        add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 266, 171, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 264, -1, -1));

        txtAlias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAliasActionPerformed(evt);
            }
        });
        txtAlias.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAliasKeyTyped(evt);
            }
        });
        add(txtAlias, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 308, 171, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alias:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 306, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Area");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 343, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Status:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(618, 373, -1, -1));

        activeRadioBtn.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(activeRadioBtn);
        activeRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        activeRadioBtn.setText("Active");
        add(activeRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 373, -1, -1));

        inActiveRadioBtn.setBackground(new java.awt.Color(0, 102, 102));
        buttonGroup1.add(inActiveRadioBtn);
        inActiveRadioBtn.setForeground(new java.awt.Color(255, 255, 255));
        inActiveRadioBtn.setText("InActive");
        inActiveRadioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inActiveRadioBtnActionPerformed(evt);
            }
        });
        add(inActiveRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 373, -1, -1));

        comboArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAreaActionPerformed(evt);
            }
        });
        add(comboArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(753, 343, 171, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void reqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqBtnActionPerformed
        int selectedRow = requestTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select the Case First", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            VictimWorkRequest v = (VictimWorkRequest) requestTable.getValueAt(selectedRow, 1);

            v.setStatus("Pending");
            v.setReceiver(account);
            populateRequestTable(emp);
        }


    }//GEN-LAST:event_reqBtnActionPerformed

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:

        int selectedRow = requestTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a request");
        } else {
            VictimWorkRequest v = (VictimWorkRequest) requestTable.getValueAt(selectedRow, 1);
            if (v.getReceiver() != null) {
                if (v.getStatus().equals("Pending")) {
                    UserAccount a = v.getSender();
                    v.setStatus("Completed");
                    JOptionPane.showMessageDialog(null, "Case Completed");
                    populateRequestTable(emp);
                    return;
                } else if (v.getStatus().equals("Reported")) {
                    JOptionPane.showMessageDialog(null, "Please Assign the Case First");
                    return;
                } else {
                    JOptionPane.showMessageDialog(null, "This case has already been completed");
                    return;
                }
            }
        }


    }//GEN-LAST:event_btnCompleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedRow = requestTable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row!");
        } else {
            
            txtCaseDesc.setText((String) requestTable.getValueAt(selectedRow, 2));
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Dealer dealer = organization.getDealerCatalog().addDealer();
        dealer.setName(txtname.getText());
        dealer.setAlias(txtAlias.getText());
        dealer.setActivityArea((String) comboArea.getSelectedItem());
        if (activeRadioBtn.isSelected()) {
            dealer.setStatus("Active");
        } else {
            dealer.setStatus("Inactive");
        }
        populateDealerTable();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtAliasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAliasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAliasActionPerformed

    private void inActiveRadioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inActiveRadioBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inActiveRadioBtnActionPerformed

    private void comboAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAreaActionPerformed

    private void txtnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c))) {
            evt.consume(); 
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtnameKeyTyped

    private void txtAliasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAliasKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c))) {
            evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtAliasKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadioBtn;
    private javax.swing.JButton btnComplete;
    private javax.swing.JButton btnDelete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboArea;
    private javax.swing.JTable dealerTable;
    private javax.swing.JRadioButton inActiveRadioBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton reqBtn;
    private javax.swing.JTable requestTable;
    private javax.swing.JTextField txtAlias;
    private javax.swing.JTextArea txtCaseDesc;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
