/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CentralRehab;

import Business.CentralRehabilitationDepartment.LocalRehabCenterDirectory;
import Business.EcoSystem;
import Business.Employee.EmployeeDirectory;
import Business.Enterprise.Enterprise;
import Business.Organization.LocalRehabCentreOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Parija
 */
public class CentralRehabWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount account;

    EcoSystem business;
    LocalRehabCentreOrganization organization;
    EmployeeDirectory employeeDirectory;
    LocalRehabCenterDirectory localRehabDirectory;

    /**
     * Creates new form CentralRehabWorkAreaJPanel
     */
    public CentralRehabWorkAreaJPanel(JPanel userProcessContainer, LocalRehabCentreOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.organization = organization;

        this.organization = organization;
        enterpriseLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageLocalPolice = new javax.swing.JButton();
        btnManageLocalPolice1 = new javax.swing.JButton();
        btnManageLocalPolice2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnManageLocalPolice.setText("Manage Local Rehabs");
        btnManageLocalPolice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnManageLocalPolice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLocalPoliceActionPerformed(evt);
            }
        });
        add(btnManageLocalPolice, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 139, 202, 139));

        btnManageLocalPolice1.setText("Manage Local UserAccount");
        btnManageLocalPolice1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnManageLocalPolice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLocalPolice1ActionPerformed(evt);
            }
        });
        add(btnManageLocalPolice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 214, 202, 64));

        btnManageLocalPolice2.setText("Manage Employee");
        btnManageLocalPolice2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnManageLocalPolice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLocalPolice2ActionPerformed(evt);
            }
        });
        add(btnManageLocalPolice2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 139, 202, 68));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("My Work Area -Adminstrative Role");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 13, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 49, 680, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageLocalPoliceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLocalPoliceActionPerformed
        ManageLocalRehabJPanel mlrjp = new ManageLocalRehabJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageLocalPoliceDepartments", mlrjp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageLocalPoliceActionPerformed

    private void btnManageLocalPolice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLocalPolice1ActionPerformed
        CentralRehabManageUserAccountJpanel lujp = new CentralRehabManageUserAccountJpanel(userProcessContainer, enterprise, organization);
        userProcessContainer.add("LocalUserAccountJPanel", lujp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);            // TODO add your handling code here:
    }//GEN-LAST:event_btnManageLocalPolice1ActionPerformed

    private void btnManageLocalPolice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLocalPolice2ActionPerformed
        // TODO add your handling code here:
        CentralRehabManageEmployeeJPanel cre = new CentralRehabManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("CentralRehabManageEmployeeJPanel", cre);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageLocalPolice2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageLocalPolice;
    private javax.swing.JButton btnManageLocalPolice1;
    private javax.swing.JButton btnManageLocalPolice2;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
