/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CentralRehab;

import Business.CentralRehabilitationDepartment.LocalRehabCenter;
import Business.CentralRehabilitationDepartment.LocalRehabCenterDirectory;
import Business.Employee.Employee;
import Business.Organization.LocalRehabCentreOrganization;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Parija
 */
public class ManageLocalRehabJPanel extends javax.swing.JPanel {

    private OrganizationDirectory organizationDirectory;
    private JPanel container;
    private LocalRehabCentreOrganization organization1;
    private Employee employee;
    private LocalRehabCenterDirectory localRehabDirectory;
    private LocalRehabCenter localRehabCenter;
    private Organization organization;

    /**
     * Creates new form ManageLocalRehabJPanel
     */
    public ManageLocalRehabJPanel(JPanel container, OrganizationDirectory organizationDirectory) {
        initComponents();
        this.container = container;
        this.organizationDirectory = organizationDirectory;
        populateComboBox();
        populateTable();
    }

    private void populateComboBox() {

        comboLocalDept.removeAllItems();
        comboLocalDept.addItem(Type.LocalRehabCentre);

    }

    private void populateTable() {

        DefaultTableModel model = (DefaultTableModel) tblLocalDept.getModel();
        model.setRowCount(0);

        for (Organization organization : organizationDirectory.getOrganizationList()) {
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboLocalDept = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLocalDept = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCreate.setText("Add a Local Rehab");
        btnCreate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 266, 171, 28));

        btnDelete.setText("Delete");
        btnDelete.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(665, 65, 103, 57));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manage a Local Rehab");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 25, -1, -1));

        comboLocalDept.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(comboLocalDept, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 226, 171, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 312, 171, -1));

        tblLocalDept.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Local Rehab"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLocalDept);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 65, 585, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sub-Organization Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 224, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed

        Type type = (Type) comboLocalDept.getSelectedItem();
        organizationDirectory.createOrganization(type);

        populateTable();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        container.remove(this);

        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JComboBox comboLocalDept;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLocalDept;
    // End of variables declaration//GEN-END:variables
}
