/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Citizen;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.LocalRehabCentreOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.CitizenWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Parija
 */
public class CitizenWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CitizenWorkAreaJPanel
     */
    JPanel userProcessContainer;
    UserAccount account;
    LocalRehabCentreOrganization citizenOrganization;
    Enterprise enterprise;
    EcoSystem system;
    ArrayList<Employee> emp;

    public CitizenWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, LocalRehabCentreOrganization citizenOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.account = account;
        this.system = system;
        this.citizenOrganization = citizenOrganization;
        setSize(1000, 1000);
        this.emp = citizenOrganization.getEmployeeDirectory().getEmployeeList();

        populateRequestAppointment(emp);
    }

    public void populateRequestAppointment(ArrayList<Employee> emp) {
        DefaultTableModel model = (DefaultTableModel) tblRequestAppointment.getModel();
        model.setRowCount(0);

        for (WorkRequest request : account.getWorkQueue().getWorkRequestList()) {
            Object[] row = new Object[3];
            row[0] = request.getAppointment();
            row[1] = request.getReceiver();
            row[2] = request.getMessage();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAppointment = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRequestAppointment = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAppointment.setText("Request an appointment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });
        add(btnAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 322, -1, 56));

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 321, 103, 58));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Citizen Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 22, -1, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("Enterprise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 69, 120, 30));

        valueLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 69, 470, 30));

        tblRequestAppointment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Appointment", "Reciever"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblRequestAppointment);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 121, 494, 168));

        jLabel2.setText("Patient's History");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 130, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
        CitizenWorkRequest citizenWorkRequest = new CitizenWorkRequest();
        citizenWorkRequest.setSender(account);
        citizenWorkRequest.setStatus("Requested");

        Organization org = null;
        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (o instanceof LocalRehabCentreOrganization) {
                        citizenWorkRequest.setStatus("Requested");
                        org = o;
                    }
                }
            }
        }
        if (org != null) {
            System.out.println("check");
            org.getWorkQueue().getWorkRequestList().add(citizenWorkRequest);
            account.getWorkQueue().getWorkRequestList().add(citizenWorkRequest);
        }
        JOptionPane.showMessageDialog(null, "Requested for Appointment");


    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblRequestAppointment;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
