/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Citizen;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Organization.CitizenOrganization;
import Business.Organization.Organization;
import Business.Role.CitizenRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Parija
 */
public class CitizenRegistrationWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CitizenRegistrationWorkAreaJPanel
     */
    JPanel container;
    UserAccount account;
    CitizenOrganization organization;
    Enterprise enterprise;
    EcoSystem system;
    Network network;

    public CitizenRegistrationWorkAreaJPanel(JPanel container, EcoSystem system, Enterprise enterprise, Network network, CitizenOrganization organization, UserAccount account) {
        initComponents();
        this.container = container;
        this.account = account;

        this.enterprise = enterprise;
        this.system = system;
        this.network = network;
        this.organization = organization;

        populateComboNetwork();

    }

    public void populateComboNetwork() {

        comboNetwork.removeAllItems();

        for (Network network : system.getNetworkList()) {
            comboNetwork.addItem(network);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        btnBack = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 252, 76, 55));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("First Name");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 58, -1, -1));

        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });
        add(txtFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 58, 180, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Personal Details");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 23, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 93, -1, -1));

        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });
        add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 93, 180, -1));

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 252, 82, 53));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 210, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("UserName");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 168, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 170, 180, -1));
        add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 212, 180, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("City");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 128, -1, -1));

        comboNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });
        add(comboNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 128, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String name = txtFName.getText() + " " + txtLName.getText();
        String username = txtUserName.getText();
        String password = String.valueOf(passwordField.getPassword());

        CitizenRole r = new CitizenRole();
        Network setNetwork = (Network) comboNetwork.getSelectedItem();

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : setNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    if (e.getEnterpriseType().equals(EnterpriseType.CentralRehabDepartment) && o.getName().equalsIgnoreCase("Local Rehab Centre")) {
                        Employee newUser = o.getEmployeeDirectory().createEmployee(name);

                        o.getUserAccountDirectory().createUserAccount(username, password, newUser, r, setNetwork.toString());
                        JOptionPane.showMessageDialog(null, "User created");
                        break;
                    }
                }

            }

        }


    }//GEN-LAST:event_btnSubmitActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
//         
    }//GEN-LAST:event_comboNetworkActionPerformed

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isAlphabetic(c))) {
            evt.consume();   
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtLNameKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox comboNetwork;
    private javax.swing.ButtonGroup genderButtonGroup;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
